name: 'Prepare for Build'
description: 'Setup java + maven, login to AWS and generate CodeArtifact token'
inputs:
  AWS_ACCOUNT:
    description: 'AWS account number where the CodeArtifact domain is located'
    required: true
    default: '401861661880'
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven # this will give cache inheritance and such cache hit and quick builds on feature branches/PRs

    # receives a JWT from the GitHub OIDC provider, and then requests an access token from AWS
    # as result we got env vars: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT }}:role/ci/builder

    - name: Generate CodeArtifact token
      shell: bash
      run: |
        TOKEN=`aws codeartifact get-authorization-token --domain agilecustoms --domain-owner ${{ inputs.AWS_ACCOUNT }} --query authorizationToken --output text`
        echo "::add-mask::$TOKEN"
        echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV
