name: Test

on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to request JWT from GitHub OIDC provider (used in 'gha-prepare-java-build' action)
      contents: read # required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Java
        uses: agilecustoms/gha-prepare-java@main
        with:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT_SHARED }}
